name       : iscan-data
version    : 1.39.0
release    : 1
source     :
    - http://support.epson.net/linux/src/scanner/iscan/iscan-data_1.39.0-1.tar.gz : 61ef9496568c8709cce7687de0d47e4b132a00fa6a398fcbb6f06f8fdf31755f
license    : GPL-2.0
component  : desktop.library
summary    : Provides the necessary support files for Image Scan! for Linux, including device information and policy file generation logic.
description: |
    Provides the necessary support files for Image Scan! for Linux, including device information and policy file generation logic.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
